# Generated by Django 5.2 on 2025-04-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email'),
        ),
        migrations.AddField(
            model_name='emailfilter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailrow',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='emails.email'),
        ),
        migrations.AddField(
            model_name='emailrow',
            name='juniper_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_rows', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='emailrow',
            name='juniper_markets',
            field=models.ManyToManyField(blank=True, related_name='email_rows', to='hotels.market'),
        ),
        migrations.AddField(
            model_name='emailrow',
            name='juniper_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_rows', to='hotels.room'),
        ),
        migrations.AddField(
            model_name='emailrow',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regex_rules', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.email'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='email_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.emailrow'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
