# Generated by Django 5.2 on 2025-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrow',
            name='hotel_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrow',
            name='room_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailrow',
            name='sale_type',
            field=models.CharField(choices=[('stop', 'Stop Sale'), ('open', 'Open Sale')], default='stop', max_length=10),
        ),
    ]
