# Generated by Django 5.2 on 2025-04-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailrow_hotel_match_score_emailrow_room_match_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrow',
            name='juniper_markets',
        ),
    ]
