# Generated by Django 5.2 on 2025-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_emailrow_juniper_markets'),
        ('hotels', '0004_alter_market_juniper_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrow',
            name='markets',
            field=models.ManyToManyField(blank=True, related_name='email_rows', to='hotels.market'),
        ),
    ]
