# Generated by Django 4.2.7 on 2025-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_market_juniper_code'),
        ('emails', '0005_emailrow_markets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrow',
            options={'ordering': ['id'], 'verbose_name': 'Email Row', 'verbose_name_plural': 'Email Rows'},
        ),
        migrations.RemoveField(
            model_name='emailrow',
            name='juniper_room',
        ),
        migrations.AddField(
            model_name='emailrow',
            name='juniper_rooms',
            field=models.ManyToManyField(blank=True, related_name='email_rows', to='hotels.room'),
        ),
    ]
