# Generated by Django 4.2.7 on 2025-04-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_alter_emailrow_options_remove_emailrow_juniper_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailrow",
            name="extracted_from_attachment",
            field=models.BooleanField(default=False),
        ),
    ]
