# Generated by Django 4.2.7 on 2025-04-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0008_email_attachment_analysis_results"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailattachment",
            options={},
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(max_length=500, upload_to="attachments/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="size",
            field=models.PositiveIntegerField(),
        ),
    ]
