# Generated by Django 4.2.7 on 2025-04-21 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0009_alter_emailattachment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrow',
            name='market',
        ),
    ]
