# Generated by Django 4.2.7 on 2025-04-22 00:44

from django.db import migrations, models
import emails.models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0011_emailrow_source_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(upload_to=emails.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
