# Generated by Django 5.2 on 2025-05-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_roomtypematch'),
        ('hotels', '0006_remove_marketalias_market_marketalias_markets'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_room_type', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('room', 'Room Not Matched'), ('hotel', 'Hotel Not Matched'), ('market', 'Market Not Matched'), ('other', 'Other')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.market')),
            ],
            options={
                'verbose_name': 'Room Type Reject',
                'verbose_name_plural': 'Room Type Rejects',
                'unique_together': {('hotel', 'email_room_type', 'market', 'reason')},
            },
        ),
    ]
