# Generated by Django 5.2 on 2025-05-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_roomtypereject'),
        ('hotels', '0006_remove_marketalias_market_marketalias_markets'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHotelMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(help_text='Gönderen e-posta adresi', max_length=255)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Eşleştirme güven puanı')),
                ('match_count', models.IntegerField(default=1, help_text='Bu eşleştirmenin kaç kez gerçekleştiği')),
                ('first_matched_at', models.DateTimeField(auto_now_add=True)),
                ('last_matched_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_matches', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Email-Hotel Match',
                'verbose_name_plural': 'Email-Hotel Matches',
                'ordering': ['-match_count', '-last_matched_at'],
                'unique_together': {('sender_email', 'hotel')},
            },
        ),
    ]
