# Generated by Django 5.2 on 2025-05-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_emailhotelmatch'),
        ('hotels', '0006_remove_marketalias_market_marketalias_markets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhotelmatch',
            options={'ordering': ('-match_count', 'sender_email'), 'verbose_name': 'E-posta Otel Eşleştirmesi', 'verbose_name_plural': 'E-posta Otel Eşleştirmeleri'},
        ),
        migrations.AlterField(
            model_name='emailhotelmatch',
            name='confidence_score',
            field=models.IntegerField(default=80, help_text='Bu eşleştirmenin güven puanı (0-100)', verbose_name='Güven Puanı'),
        ),
        migrations.AlterField(
            model_name='emailhotelmatch',
            name='first_matched_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İlk Eşleştirme'),
        ),
        migrations.AlterField(
            model_name='emailhotelmatch',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_matches', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AlterField(
            model_name='emailhotelmatch',
            name='last_matched_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Eşleştirme'),
        ),
        migrations.AlterField(
            model_name='emailhotelmatch',
            name='match_count',
            field=models.IntegerField(default=1, help_text='Kaç kez eşleştirildi', verbose_name='Eşleştirme Sayısı'),
        ),
        migrations.AlterField(
            model_name='emailhotelmatch',
            name='sender_email',
            field=models.EmailField(help_text='E-posta gönderenin adresi', max_length=254, verbose_name='Gönderen E-posta'),
        ),
    ]
