# Generated by Django 5.2 on 2025-05-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rejected_hotel_not_found', 'Rejected - JP Hotel Not Found'), ('rejected_room_not_found', 'Rejected - JP Room Not Found'), ('manual_processed', 'Manual Processed'), ('sent_to_robot', 'Sent to Robot'), ('robot_processed', 'Robot Processed'), ('processing', 'Processing'), ('processed_nodata', 'No Data Found'), ('ignored', 'Ignored'), ('error', 'Error')], default='pending', max_length=50),
        ),
    ]
