# Generated by Django 5.2 on 2025-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_alter_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='content_id',
            field=models.CharField(blank=True, help_text='Content-ID header from email', max_length=255, null=True),
        ),
    ] 