# Generated by Django 5.2 on 2025-05-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0022_robotconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrow',
            name='selected_contracts',
            field=models.CharField(blank=True, help_text='Comma-separated list of selected contracts', max_length=500, null=True),
        ),
    ]
