# Generated by Django 5.2 on 2025-05-22 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0024_emailrow_original_market_name_emailcontractmatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rejected_hotel_not_found', 'Rejected - JP Hotel Not Found'), ('rejected_room_not_found', 'Rejected - JP Room Not Found'), ('blocked_hotel_not_found', 'Blocked - JP Hotel Not Found'), ('manual_processed', 'Manual Processed'), ('sent_to_robot', 'Sent to Robot'), ('robot_processed', 'Robot Processed'), ('juniper_manual', 'Juniper(M)'), ('juniper_robot', 'Juniper(R)'), ('processing', 'Processing'), ('processed_nodata', 'No Data Found'), ('ignored', 'Ignored'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='EmailBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='Bloklanacak e-posta adresi', max_length=254, unique=True, verbose_name='Gönderen E-posta')),
                ('reason', models.CharField(default='JP Hotel Not Found', help_text='E-postanın bloklanma nedeni', max_length=100, verbose_name='Bloklanma Nedeni')),
                ('is_active', models.BooleanField(default=True, help_text='Blok aktif mi? Geçici olarak devre dışı bırakmak için kapatabilirsiniz.', verbose_name='Aktif Mi?')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloklanma Tarihi')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme')),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_emails', to=settings.AUTH_USER_MODEL, verbose_name='Bloklayan Kullanıcı')),
                ('original_email', models.ForeignKey(help_text='Bloklamaya neden olan orijinal e-posta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_blocks', to='emails.email', verbose_name='Orijinal E-posta')),
            ],
            options={
                'verbose_name': 'E-posta Blok Listesi',
                'verbose_name_plural': 'E-posta Blok Listesi',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
