# Generated by Django 5.2 on 2025-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('token_usage', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Performance Metric',
                'verbose_name_plural': 'AI Performance Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HotelAICounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unedited_approvals', models.IntegerField(default=0)),
                ('edited_approvals', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=10)),
                ('use_regex', models.BooleanField(default=False)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotel AI Counter',
                'verbose_name_plural': 'Hotel AI Counters',
                'ordering': ['hotel__juniper_hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
