# Generated by Django 5.2 on 2025-04-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emails', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiperformancemetric',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='emails.aimodel'),
        ),
        migrations.AddField(
            model_name='aiperformancemetric',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='emails.prompt'),
        ),
        migrations.AddField(
            model_name='hotelaicounter',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_counters', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='email_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='emails.emailrow'),
        ),
        migrations.AlterUniqueTogether(
            name='aiperformancemetric',
            unique_together={('ai_model', 'prompt', 'date')},
        ),
    ]
