# Generated by Django 5.2 on 2025-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('default_from_email', models.EmailField(default='stopsale@example.com', max_length=254)),
                ('email_subject_prefix', models.CharField(default='[StopSale] ', max_length=50)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password', models.CharField(blank=True, max_length=255)),
                ('imap_folder', models.CharField(default='INBOX', max_length=50)),
                ('imap_check_interval', models.IntegerField(default=300, help_text='Check interval in seconds')),
                ('is_active', models.BooleanField(default=False, help_text='Set to true to enable email checking')),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
