# Generated by Django 5.2 on 2025-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='delete_after_processing',
            field=models.BooleanField(default=False, help_text='Delete .eml files after processing'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='local_email_folder',
            field=models.CharField(blank=True, help_text='Path to local folder with .eml files', max_length=255),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='move_to_folder',
            field=models.CharField(blank=True, help_text='Path to move processed .eml files (leave blank to not move)', max_length=255),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='process_subdirectories',
            field=models.BooleanField(default=False, help_text='Process .eml files in subdirectories'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='use_local_folder',
            field=models.BooleanField(default=False, help_text='Use local folder for emails instead of IMAP'),
        ),
    ]
