# Generated by Django 5.2 on 2025-04-11 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailconfiguration_delete_after_processing_and_more'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSuccessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.IntegerField(default=0, help_text='Number of successful analyses without editing')),
                ('total_count', models.IntegerField(default=0, help_text='Total number of analyses for this hotel')),
                ('last_edited_at', models.DateTimeField(blank=True, help_text='When analysis was last edited', null=True)),
                ('use_regex', models.BooleanField(default=False, help_text='Whether to use regex instead of AI for this hotel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='success_analysis', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('hotel_name', 'Hotel Name'), ('room_type', 'Room Type'), ('market', 'Market'), ('date_range', 'Date Range'), ('sale_type', 'Sale Type'), ('other', 'Other')], max_length=20)),
                ('pattern', models.TextField(help_text='Regular expression pattern to match in email content')),
                ('success_count', models.IntegerField(default=0, help_text='Number of times this rule was used successfully')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
