# Generated by Django 5.2 on 2025-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hotelsuccessanalysis_regexrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=20)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='HotelSuccessAnalysis',
        ),
        migrations.DeleteModel(
            name='RegexRule',
        ),
    ]
