# Generated by Django 5.2 on 2025-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_databasebackup_remove_regexrule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='imap_label',
            field=models.CharField(blank=True, default='stop_sale', help_text='Gmail label to filter emails by (leave empty to process all emails)', max_length=50),
        ),
    ]
