# Generated by Django 5.2 on 2025-05-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailconfiguration_imap_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='imap_label',
            field=models.CharField(blank=True, default='stop_sale', help_text='Gmail/IMAP label or folder to filter emails by. If specified, the system will only process emails from this label/folder instead of the inbox. For Gmail, create a label named "stop_sale" and apply it to relevant emails.', max_length=50),
        ),
    ]
