# Generated by Django 5.2 on 2025-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_recreate_market_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniperMarketCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='juniper_codes', to='hotels.market')),
            ],
            options={
                'verbose_name': 'Juniper Market Code',
                'verbose_name_plural': 'Juniper Market Codes',
                'ordering': ['market__name', 'code'],
                'unique_together': {('market', 'code')},
            },
        ),
    ]
