# Generated by Django 5.2 on 2025-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20250412_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='juniper_code',
            field=models.CharField(blank=True, help_text='Eski kodlar için (geriye dönük uyumluluk)', max_length=50, null=True),
        ),
    ]
