# Generated by Django 4.2.7 on 2025-04-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_alter_market_juniper_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        db_index=True,
                        help_text="The market name variation as found in emails (case-insensitive matching recommended during lookup).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market",
                    models.ForeignKey(
                        help_text="The canonical Juniper Market this alias maps to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="hotels.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Alias",
                "verbose_name_plural": "Market Aliases",
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="JuniperContractMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(
                        help_text="Name of the allotment contract (e.g., 'Summer 2025 EURO').",
                        max_length=255,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="Season code (e.g., 'S25').",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        help_text="The hotel this contract applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_markets",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        help_text="The specific Juniper Market included in this contract.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="hotels.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Juniper Contract Market",
                "verbose_name_plural": "Juniper Contract Markets",
                "ordering": [
                    "hotel__juniper_code",
                    "contract_name",
                    "season",
                    "market__name",
                ],
                "unique_together": {("hotel", "contract_name", "season", "market")},
            },
        ),
    ]
