# Generated by Django 5.2 on 2025-05-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_junipercontractmarket_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group_name',
            field=models.CharField(default='DEFAULT', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotelLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_hotel_name', models.CharField(help_text='Original hotel name as found in email', max_length=255, unique=True)),
                ('confidence', models.FloatField(default=0.8, help_text='Confidence score for this match (0.0-1.0)')),
                ('frequency', models.IntegerField(default=1, help_text='How many times this mapping has been confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_learnings', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-confidence', '-frequency'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_groups', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__juniper_hotel_name', 'name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomTypeGroupLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_room_type', models.CharField(help_text='Original room name as found in email', max_length=255)),
                ('confidence', models.FloatField(default=0.8, help_text='Confidence score for this match (0.0-1.0)')),
                ('frequency', models.IntegerField(default=1, help_text='How many times this mapping has been confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='hotels.roomtypegroup')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_learnings', to='hotels.hotel')),
                ('juniper_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='hotels.room')),
            ],
            options={
                'ordering': ['-confidence', '-frequency'],
                'unique_together': {('hotel', 'mail_room_type')},
            },
        ),
        migrations.CreateModel(
            name='RoomTypeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Original room type name as found in emails', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='hotels.roomtypegroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='hotels.room')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'room'], name='hotels_room_group_i_07169b_idx')],
                'unique_together': {('group', 'room', 'original_name')},
            },
        ),
    ]
