# Generated by Django 5.2 on 2025-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_room_group_name_hotellearning_roomtypegroup_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtypevariant',
            unique_together={('group', 'room', 'variant_room_name')},
        ),
        migrations.AddField(
            model_name='roomtypevariant',
            name='variant_room_name',
            field=models.CharField(default='DEFAULT', help_text='Specific Juniper room name/type that belongs to this group', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtypegroup',
            name='name',
            field=models.CharField(db_index=True, help_text='Normalized group name like STANDARD, DELUXE, etc.', max_length=255),
        ),
        migrations.RemoveField(
            model_name='roomtypevariant',
            name='original_name',
        ),
    ]
