# Generated by Django 5.2 on 2025-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_roomtypevariant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roomtypevariant',
            name='hotels_room_group_i_07169b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='roomtypevariant',
            unique_together={('group', 'variant_room_name')},
        ),
        migrations.AddIndex(
            model_name='roomtypevariant',
            index=models.Index(fields=['group'], name='hotels_room_group_i_b9e9f4_idx'),
        ),
        migrations.RemoveField(
            model_name='roomtypevariant',
            name='room',
        ),
    ]
